CREATE SEQUENCE IF NOT EXISTS SEQ_BIGCORP_USER_ID AS BIGINT START WITH 1 ;
CREATE SEQUENCE IF NOT EXISTS SEQ_RESTAURANT_ID AS BIGINT START WITH 1 ;
CREATE SEQUENCE IF NOT EXISTS SEQ_RESTAURANT_TYPE_ID AS BIGINT START WITH 1 ;